[
    {
        "content": "<p>Hi, am adding few features to Zulip, and i have an installation (production) running.<br>\nPlease how to deploy my development version in production from my Repo github into the existing regular installation.</p>\n<p>Thanks</p>",
        "id": 1309521,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642039569
    },
    {
        "content": "<p><a href=\"https://zulip.readthedocs.io/en/latest/production/upgrade-or-modify.html#upgrading-from-a-git-repository\">https://zulip.readthedocs.io/en/latest/production/upgrade-or-modify.html#upgrading-from-a-git-repository</a> has a section about setting <code>git_repo_url</code> in <code>/etc/zulip/zulip.com</code></p>",
        "id": 1309528,
        "sender_full_name": "Alex Vandiver",
        "timestamp": 1642043542
    },
    {
        "content": "<p>amazing.. thanks a lot</p>",
        "id": 1309536,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642044862
    },
    {
        "content": "<p>I was able to start the process but it fail because of password authentication on the db... It required to do it with zulip user but am connected as root right now</p>",
        "id": 1309630,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642077794
    },
    {
        "content": "<p><a href=\"/user_uploads/2/96/o-N93MECueMP_6mskT6Dhxt_/Capture-décran-2022-01-13-à-13.44.49.png\">Capture-décran-2022-01-13-à-13.44.49.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/96/o-N93MECueMP_6mskT6Dhxt_/Capture-décran-2022-01-13-à-13.44.49.png\" title=\"Capture-décran-2022-01-13-à-13.44.49.png\"><img src=\"/user_uploads/2/96/o-N93MECueMP_6mskT6Dhxt_/Capture-décran-2022-01-13-à-13.44.49.png\"></a></div>",
        "id": 1309633,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642077923
    },
    {
        "content": "<p>i already have a password for that user defined in the zulip secret file</p>",
        "id": 1309635,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642077954
    },
    {
        "content": "<p>am fetching the upgrade from a git repo with my version with some little modifications</p>",
        "id": 1309636,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642077985
    },
    {
        "content": "<p><a href=\"/user_uploads/2/a8/zRr7FlrLvSzA_ZJBcTSg5SxW/Capture-décran-2022-01-13-à-13.44.49.png\">Capture-décran-2022-01-13-à-13.44.49.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/a8/zRr7FlrLvSzA_ZJBcTSg5SxW/Capture-décran-2022-01-13-à-13.44.49.png\" title=\"Capture-décran-2022-01-13-à-13.44.49.png\"><img src=\"/user_uploads/2/a8/zRr7FlrLvSzA_ZJBcTSg5SxW/Capture-décran-2022-01-13-à-13.44.49.png\"></a></div>",
        "id": 1309661,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642086608
    },
    {
        "content": "<p>Hi Am having an issue connecting to the db when connecting to the db while making the upgrade from git</p>",
        "id": 1309662,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642086732
    },
    {
        "content": "<p><a href=\"/user_uploads/2/41/81VeGZ65VYWgmnYqPpO4fRtc/Capture-décran-2022-01-13-à-13.44.49.png\">Capture-décran-2022-01-13-à-13.44.49.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/2/41/81VeGZ65VYWgmnYqPpO4fRtc/Capture-décran-2022-01-13-à-13.44.49.png\" title=\"Capture-décran-2022-01-13-à-13.44.49.png\"><img src=\"/user_uploads/2/41/81VeGZ65VYWgmnYqPpO4fRtc/Capture-décran-2022-01-13-à-13.44.49.png\"></a></div>",
        "id": 1309663,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642086743
    },
    {
        "content": "<p>Am doing it as <code>root</code> user</p>",
        "id": 1309664,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642086758
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"22633\">@adonissimo</span> I just collected your questions from three separate topics where you posted them. Please be careful to post all related questions to the same topic, so that folks who are trying to help you can see all the context.</p>",
        "id": 1309719,
        "sender_full_name": "Alya Abbott",
        "timestamp": 1642095620
    },
    {
        "content": "<p>It is also generally best to use code blocks rather than screenshots to post terminal output.</p>",
        "id": 1309721,
        "sender_full_name": "Alya Abbott",
        "timestamp": 1642095656
    },
    {
        "content": "<p>okay thank you <span class=\"user-mention\" data-user-id=\"19257\">@Alya Abbott</span></p>",
        "id": 1309764,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642102527
    },
    {
        "content": "<p>i still havent figure out the solution, i have even added <code>zulip</code> user to sudeors</p>",
        "id": 1309765,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642102558
    },
    {
        "content": "<p>Do not add the <code>zulip</code> user to sudoers. Your errors have nothing to do with <code>sudo</code>, and the privilege separation is there for a reason.</p>",
        "id": 1309766,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1642102651
    },
    {
        "content": "<p>Your screenshots show errors with PostgreSQL authentication. The PostgreSQL account is separate from the system account.</p>",
        "id": 1309767,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1642102721
    },
    {
        "content": "<p>So what should i do... since i made the initial installation according to what is written in the documentation. Any tips please ?</p>",
        "id": 1309769,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642102928
    },
    {
        "content": "<p>A normal server installation with the database on <code>localhost</code> will not have a PostgreSQL password; it uses PostgreSQL peer authentication.</p>",
        "id": 1309772,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1642103306
    },
    {
        "content": "<p>Why did you configure a password? And how exactly did you do so—have you tested that PostgreSQL accepts that password?</p>",
        "id": 1309773,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1642103353
    },
    {
        "content": "<p>i have defined a password in the <code>/etc/zulip/zulip-secret.conf</code> file</p>",
        "id": 1309774,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642103402
    },
    {
        "content": "<p>Well, just because you put a password there doesn’t make it the right password. Most likely you just need to remove that line.</p>",
        "id": 1309775,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1642103442
    },
    {
        "content": "<p>Okay... am actually making a test without the password .</p>",
        "id": 1309776,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642103483
    },
    {
        "content": "<p>humm it actually work without the password. So I assume the PostgreSQL server is using <code>ident</code> auth method</p>",
        "id": 1309778,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642103572
    },
    {
        "content": "<p>It’s using peer authentication. (This is different from ident in that it uses kernel features, not an ident daemon.)</p>",
        "id": 1309779,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1642103762
    },
    {
        "content": "<p>okay i understand</p>",
        "id": 1309782,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642104203
    },
    {
        "content": "<p>Now am having this as error when i use a password to connect to  PostgreSQL</p>\n<div class=\"codehilite\"><pre><span></span><code>Traceback (most recent call last):\n  File &quot;/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py&quot;, line 219, in ensure_connection\n    self.connect()\n  File &quot;/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py&quot;, line 33, in inner\n    return func(*args, **kwargs)\n  File &quot;/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/base/base.py&quot;, line 200, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File &quot;/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/utils/asyncio.py&quot;, line 33, in inner\n    return func(*args, **kwargs)\n  File &quot;/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py&quot;, line 187, in get_new_connection\n    connection = Database.connect(**conn_params)\n  File &quot;/srv/zulip-venv-cache/3a9126a70136bb012ac5d3e4318beeb1c3b2244c/zulip-py3-venv/lib/python3.8/site-packages/psycopg2/__init__.py&quot;, line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File &quot;/home/zulip/deployments/2021-12-06-16-04-50/zerver/lib/db.py&quot;, line 47, in __init__\n    super().__init__(*args, **kwargs)\npsycopg2.OperationalError: connection to server on socket &quot;/var/run/postgresql/.s.PGSQL.5432&quot; failed: fe_sendauth: no password supplied\n</code></pre></div>\n<p>Any idea where the <code>fe_sendauth</code>  is comming from ?</p>",
        "id": 1309790,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642104946
    },
    {
        "content": "<p>It's done. Thank you <span class=\"user-mention\" data-user-id=\"699\">@Anders Kaseorg</span>  for responding meand hints</p>",
        "id": 1309815,
        "sender_full_name": "Adonis SIMO",
        "timestamp": 1642106500
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"22633\">adonissimo</span> has marked this topic as resolved.</p>",
        "id": 1310356,
        "sender_full_name": "Notification Bot",
        "timestamp": 1642164195
    }
]