[
    {
        "content": "<p>Hello, I'm running into some issues installing Zulip on a freshly installed VPS running Ubuntu 16.04.</p>",
        "id": 51363,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735298
    },
    {
        "content": "<p>Here are a few snips from the install log:</p>",
        "id": 51364,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735373
    },
    {
        "content": "<p>Notice: /Stage[main]/Zulip::Postgres_appdb_tuned/Exec[pg_ctlcluster 9.5 main restart]/returns: Job for <a href=\"mailto:postgresql@9.5-main.service\" title=\"mailto:postgresql@9.5-main.service\">postgresql@9.5-main.service</a> failed because the control process exited with error code. See \"systemctl status <a href=\"mailto:postgresql@9.5-main.service\" title=\"mailto:postgresql@9.5-main.service\">postgresql@9.5-main.service</a>\" and \"journalctl -xe\" for details.<br>\nError: /Stage[main]/Zulip::Postgres_appdb_tuned/Exec[pg_ctlcluster 9.5 main restart]: Failed to call refresh: pg_ctlcluster 9.5 main restart returned 1 instead of one of [0]<br>\nError: /Stage[main]/Zulip::Postgres_appdb_tuned/Exec[pg_ctlcluster 9.5 main restart]: pg_ctlcluster 9.5 main restart returned 1 instead of one of [0]<br>\nNotice: /Stage[main]/Zulip::Base/File[/usr/lib/nagios/plugins/zulip_base]/ensure: created<br>\nNotice: /Stage[main]/Zulip::Base/File[/usr/lib/nagios/plugins/zulip_base/check_debian_packages]/ensure: defined content as '{md5}b5eac9a9df7c09d9cfd73249b0447dae'<br>\nNotice: /Stage[main]/Zulip::Supervisor/Exec[enable supervisor]/returns: Failed to execute operation: No such file or directory<br>\nError: systemctl enable supervisor returned 1 instead of one of [0]<br>\nError: /Stage[main]/Zulip::Supervisor/Exec[enable supervisor]/returns: change from notrun to 0 failed: systemctl enable supervisor returned 1 instead of one of [0]</p>",
        "id": 51365,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735388
    },
    {
        "content": "<p>OK, sounds like postgres failed to start on your system</p>",
        "id": 51366,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1478735450
    },
    {
        "content": "<p>when I run 'systemctl status <a href=\"mailto:postgresql@9.5-main.service\" title=\"mailto:postgresql@9.5-main.service\">postgresql@9.5-main.service</a>', it returns saying there is a configuration error in the config file</p>",
        "id": 51367,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735483
    },
    {
        "content": "<p>Interesting.  What VPS provider are you using?</p>",
        "id": 51368,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1478735498
    },
    {
        "content": "<p>Through b-host</p>",
        "id": 51369,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735541
    },
    {
        "content": "<p>not the best, but it's dirt cheap</p>",
        "id": 51370,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735589
    },
    {
        "content": "<p>could this be avoided by maybe finding a default postgres config file? Assuming Zulip changes it as needed..</p>",
        "id": 51371,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478735982
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-email=\"leightonstarwalt@gmail.com\">@Leighton Starwalt</span> Sorry for the slow reply -- I went AFK.  I'm not sure whether a default postgres config file would work; I would guess something else is busted with the system, since Zulip has likely already changed the postgres config file.  I would try debugging by looking at the postgres server startup logs.  </p>",
        "id": 51381,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1478747469
    },
    {
        "content": "<p>Hey Tim, no worries.</p>",
        "id": 52030,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478815760
    },
    {
        "content": "<p>I looked at the logs and it turns out it's an issue with locale settings.. so, I ran <strong>locale-gen en_US en_US.UTF-8</strong> and re-ran the install.. and it works!</p>",
        "id": 52035,
        "sender_full_name": "Leighton Starwalt",
        "timestamp": 1478815861
    },
    {
        "content": "<p>Great!  I wonder if there's a way we could test for the locale not being setup properly</p>",
        "id": 52036,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1478815899
    },
    {
        "content": "<p>I just set-up a clean install of Debian 11 in a VMware-hosted VM to install Zulip, but the install script fails with an exit code of 134. The last line of the log is \"Reading package lists.../root/zulip-server-4.9/scripts/lib/setup-apt-repo: line 53:  3100 Aborted                 apt-get update\"</p>",
        "id": 1322332,
        "sender_full_name": "Michael Hall",
        "timestamp": 1643939016
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"23087\">@Michael Hall</span> that sounds like a networking problem -- <code>apt-get update</code> is just the Debian system updater.</p>",
        "id": 1322752,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1644015967
    },
    {
        "content": "<p>We'll be able to help more if you can paste the whole traceback in a code block.</p>",
        "id": 1322753,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1644015980
    }
]