[
    {
        "content": "<p>Hi. I am getting an error while updateing from git master:</p>\n<p>Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-install-bpt2mgmq/talon/<br>\nYou are using pip version 19.0.1, however version 19.0.3 is available.<br>\nYou should consider upgrading via the 'pip install --upgrade pip' command.</p>\n<p>Error running a subcommand of /home/zulip/deployments/2019-02-26-13-27-40/scripts/lib/create-production-venv: /srv/zulip-venv-cache/4cfed786731bb9f2347553f7edb35ee4667b71cb/zulip-py3-venv/bin/pip install --no-deps --requirement /home/zulip/deployments/2019-02-26-13-27-40/requirements/prod.txt<br>\nActual error output for the subcommand is just above this.</p>",
        "id": 707795,
        "sender_full_name": "Fabian Tribrunner",
        "timestamp": 1551184223
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"8768\">@Fabian Tribrunner</span> can you post the output above what you posted?  It's pretty clear from that output that this is not the actual error.</p>",
        "id": 708193,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1551206619
    },
    {
        "content": "<p>(The <code>pip</code> thing you displayed is a warning that <code>pip</code> prints about new versions being available, and isn't interesting)</p>",
        "id": 708194,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1551206626
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"7\">@Tim Abbott</span>  i thought that too. but the update does not run through....</p>",
        "id": 708277,
        "sender_full_name": "Fabian Tribrunner",
        "timestamp": 1551210240
    },
    {
        "content": "<p>I will try to reproduce it later.</p>",
        "id": 708311,
        "sender_full_name": "Fabian Tribrunner",
        "timestamp": 1551210696
    }
]