[
    {
        "content": "<p>I'm new to Zulip and just installed it for the first time via Docker containers, and I'm having an issue authenticating users via LDAP.  I'm running FreeIPA on an external host, which I can query fine from the Zulip container (both via ldapsearch and 'manage.py query_ldap', the latter of which returns proper 'full_name' and 'email' properties from the LDAP user object).</p>\n<p>I've tried configuring the relevant parameters in settings.py in the right combinations for each of the three methods outlined in the docs (i.e. Email search, user search with appended email domain, and user search with associated email property), restarting the services after each modification.</p>\n<p>Because the lookups seem to work via 'query_ldap', I began to suspect I may have gotten things into an obscure broken state somehow, and started inspecting Python objects for clues.</p>",
        "id": 1184486,
        "sender_full_name": "Denizen",
        "timestamp": 1621469227
    },
    {
        "content": "<p>Perhaps it's an issue that \"ldap_auth_enabled\" returns \"False\"? </p>\n<p>(Despite 'zproject.backends.ZulipLDAPUserPopulator' being listed in 'AUTHENTICATION_BACKENDS', and 'zproject.backends.ZulipLDAPAuthBackend' being specified in \"settings.py\".)</p>",
        "id": 1184487,
        "sender_full_name": "Denizen",
        "timestamp": 1621469523
    },
    {
        "content": "<p>Is LDAP authentication enabled in your organization settings (<span aria-label=\"gear\" class=\"emoji emoji-2699\" role=\"img\" title=\"gear\">:gear:</span> → <strong>Manage organization</strong> → <strong>Authentication methods</strong>)?</p>",
        "id": 1184489,
        "sender_full_name": "Anders Kaseorg",
        "timestamp": 1621469708
    },
    {
        "content": "<p>Yes.</p>",
        "id": 1184492,
        "sender_full_name": "Denizen",
        "timestamp": 1621469937
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"20129\">@Denizen</span> hmm, <code>ldap_auth_enabled</code> is a function only of two things: </p>\n<ul>\n<li>Whether <code>LDAPAuthBackend</code> is enabled in <code>settings.py</code></li>\n<li>The <code>Authentication methods</code> thing <span class=\"user-mention silent\" data-user-id=\"699\">Anders Kaseorg</span> mentioned.</li>\n</ul>\n<p>So I'd double-check that you restarted your server; what you describe should be a correct configuration.</p>",
        "id": 1184644,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1621489564
    },
    {
        "content": "<p>Heh,  well that appears to have worked that time.</p>\n<p>So I had been using both \"restart-server\"  and \"supervisorctl restart all\"... Is the latter a less thorough restart?</p>",
        "id": 1184658,
        "sender_full_name": "Denizen",
        "timestamp": 1621490200
    },
    {
        "content": "<p>Well, the former flushes caches, so yes, there could be a difference.</p>",
        "id": 1184660,
        "sender_full_name": "Tim Abbott",
        "timestamp": 1621490296
    },
    {
        "content": "<p>Ah, maybe that's what it was then.  Thanks!</p>\n<p>(I was just about to dive into \"backends.py\" :) )</p>",
        "id": 1184661,
        "sender_full_name": "Denizen",
        "timestamp": 1621490387
    }
]